global:
  dynamic:
    plugins:
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/dynatrace-backstage-plugin-dql:pr_791__2.2.0!dynatrace-backstage-plugin-dql
        disabled: false
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/dynatrace-backstage-plugin-dql-backend:pr_791__2.2.0!dynatrace-backstage-plugin-dql-backend
        disabled: false