global:
  #test
  dynamic:
    plugins:
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/dynatrace-backstage-plugin-dql:pr_791__2.2.0!dynatrace-backstage-plugin-dql
        disabled: false
        pluginConfig:
          dynatrace:
            environments:
              - name: test
                url: https://test.com
                tokenUrl: https://test.com
                accountUrn: test
                clientId: test
                clientSecret: test

      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/dynatrace-backstage-plugin-dql-backend:pr_791__2.2.0!dynatrace-backstage-plugin-dql-backend-dynamic
        disabled: false